### ISSUE TITLE
Linux build broken

### ISSUE THREAD

**Issue by sakulstra** [nickgillian/grt#19]
Hello,
it seems like the grt-gui linux build is broken since 54ecf041c1cb25c7b7db88ef610d7ef81dbc3e52 ```

```grt/gui/GRT/mainwindow.h:280: error: 'SwipeDetector' in namespace 'GRT' does not name a type
     GRT::SwipeDetector swipeDetector;
     ^```
Regards,
Lukas

**Comment by cyberluke** [comment]
Hello, yesterday I built it for Debian on both x86 and arm architecture. Can you try it again with the latest sources?

**Comment by nickgillian** [comment]
With the current build, things are building on Ubuntu (14.04) with no errors.  Can you confirm sakulstra is this is still an issue?
